Repository InnerCircle-ICD3/be-onboarding-project, pull requests merged in 2025-03, with the labels that each got.

#24 초기 프로젝트 생성
  project/sangkyeong-onboarding/.gitattributes
  project/sangkyeong-onboarding/.gitignore
  project/sangkyeong-onboarding/build.gradle.kts
  project/sangkyeong-onboarding/gradle/wrapper/gradle-wrapper.jar
  project/sangkyeong-onboarding/gradle/wrapper/gradle-wrapper.properties
  project/sangkyeong-onboarding/gradlew
  project/sangkyeong-onboarding/gradlew.bat
  project/sangkyeong-onboarding/settings.gradle.kts
  project/sangkyeong-onboarding/src/main/kotlin/org/innercircle/survey/SangkyeongOnboardingApplication.kt
  project/sangkyeong-onboarding/src/main/resources/application.properties
  project/sangkyeong-onboarding/src/test/kotlin/org/innercircle/survey/SangkyeongOnboardingApplicationTests.kt
Labels: enhancement

#51 설문조사와 설문 받을 항목, 항목 입력 형태 Entity 작성
  project/wonjun-onboarding/src/main/kotlin/com/onboarding/form/domain/Item.kt
  project/wonjun-onboarding/src/main/kotlin/com/onboarding/form/domain/ItemType.kt
  project/wonjun-onboarding/src/main/kotlin/com/onboarding/form/domain/Survey.kt
Labels: Leader Session

#71 docs: 테이블 설계
  project/taehwan-onboarding/README.md
  project/taehwan-onboarding/ddl/item.sql
  project/taehwan-onboarding/ddl/item_option.sql
  project/taehwan-onboarding/ddl/survey.sql
  project/taehwan-onboarding/ddl/survey_response.sql
  project/taehwan-onboarding/ddl/survey_response_item.sql
  project/taehwan-onboarding/erd.png
  project/taehwan-onboarding/img.png
Labels: Leader Archive

#62 멀티모듈 프로젝트 틀 구성 및 의존성 설정
  project/hjpark-onboarding/README.md
  project/hjpark-onboarding/build.gradle.kts
  project/hjpark-onboarding/gradle.properties
  project/hjpark-onboarding/gradle/libs.versions.toml
  project/hjpark-onboarding/gradle/wrapper/gradle-wrapper.jar
  project/hjpark-onboarding/gradle/wrapper/gradle-wrapper.properties
  project/hjpark-onboarding/gradlew
  project/hjpark-onboarding/gradlew.bat
  project/hjpark-onboarding/settings.gradle.kts
  project/hjpark-onboarding/src/main/resources/application.yml
  project/hjpark-onboarding/support/logging/build.gradle.kts
  project/hjpark-onboarding/support/logging/src/main/resources/logback/logback-local.xml
  project/hjpark-onboarding/support/logging/src/main/resources/logging.yml
  project/hjpark-onboarding/support/shared-common/build.gradle.kts
  project/hjpark-onboarding/survey/api/build.gradle.kts
  project/hjpark-onboarding/survey/api/src/main/kotlin/com/hjpark/survey/SurveyApplication.kt
  project/hjpark-onboarding/survey/api/src/main/kotlin/com/hjpark/survey/config/SwaggerConfig.kt
  project/hjpark-onboarding/survey/api/src/main/resources/application-dev.yml
  project/hjpark-onboarding/survey/api/src/main/resources/application-local.yml
  project/hjpark-onboarding/survey/api/src/main/resources/application-prod.yml
  project/hjpark-onboarding/survey/api/src/main/resources/application.yml
  project/hjpark-onboarding/survey/api/src/test/kotlin/com/hjpark/survey/SurveyApplicationTest.kt
  project/hjpark-onboarding/survey/api/src/test/resources/application.yml
  project/hjpark-onboarding/survey/application/build.gradle.kts
  project/hjpark-onboarding/survey/build.gradle.kts
  project/hjpark-onboarding/survey/data/build.gradle.kts
  project/hjpark-onboarding/survey/domain/build.gradle.kts
Labels: Leader Archive
